// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "widget.h"

void Widget::cb_headerImage_i(Avtk::Image*, void*) {
  //system("xdg-open http://www.openavproductions.com/artyfx#ducka");
}
void Widget::cb_headerImage(Avtk::Image* o, void* v) {
  ((Widget*)(o->parent()->user_data()))->cb_headerImage_i(o,v);
}

void Widget::cb_graph_i(Avtk::Waveshaper* o, void*) {
  float tmp = o->value();
distortion->value( tmp );
writePort(SATMA_DISTORTION, tmp);

envelope->value( o->getEnvelope() );

float a = o->getActive();
writePort(SATMA_ACTIVE, a);
//printf("active %f\n", a );
}
void Widget::cb_graph(Avtk::Waveshaper* o, void* v) {
  ((Widget*)(o->parent()->user_data()))->cb_graph_i(o,v);
}

void Widget::cb_envelope_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
graph->setEnvelope( tmp );
writePort(SATMA_TONE, tmp);
}
void Widget::cb_envelope(Avtk::Dial* o, void* v) {
  ((Widget*)(o->parent()->user_data()))->cb_envelope_i(o,v);
}

void Widget::cb_distortion_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
graph->value( tmp );
writePort(SATMA_DISTORTION, tmp);
}
void Widget::cb_distortion(Avtk::Dial* o, void* v) {
  ((Widget*)(o->parent()->user_data()))->cb_distortion_i(o,v);
}

/**
   if the type of filter changes, this function will highlight the right button
*/
void Widget::update_button(int button) {
}

Widget::Widget() {
  { Fl_Double_Window* o = window = new Fl_Double_Window(160, 220);
    window->user_data((void*)(this));
    { headerImage = new Avtk::Image(0, 0, 160, 29, "header.png");
      headerImage->box(FL_NO_BOX);
      headerImage->color(FL_BACKGROUND_COLOR);
      headerImage->selection_color(FL_BACKGROUND_COLOR);
      headerImage->labeltype(FL_NORMAL_LABEL);
      headerImage->labelfont(0);
      headerImage->labelsize(14);
      headerImage->labelcolor((Fl_Color)20);
      headerImage->callback((Fl_Callback*)cb_headerImage);
      headerImage->align(Fl_Align(FL_ALIGN_CENTER));
      headerImage->when(FL_WHEN_RELEASE_ALWAYS);
      headerImage->setPixbuf(header.pixel_data,4);
    } // Avtk::Image* headerImage
    { graph = new Avtk::Waveshaper(5, 36, 150, 126, "graph");
      graph->box(FL_UP_BOX);
      graph->color((Fl_Color)179);
      graph->selection_color(FL_INACTIVE_COLOR);
      graph->labeltype(FL_NO_LABEL);
      graph->labelfont(0);
      graph->labelsize(14);
      graph->labelcolor(FL_FOREGROUND_COLOR);
      graph->callback((Fl_Callback*)cb_graph);
      graph->align(Fl_Align(FL_ALIGN_BOTTOM));
      graph->when(FL_WHEN_CHANGED);
    } // Avtk::Waveshaper* graph
    { envelope = new Avtk::Dial(93, 169, 38, 37, "Tone");
      envelope->box(FL_NO_BOX);
      envelope->color((Fl_Color)90);
      envelope->selection_color(FL_INACTIVE_COLOR);
      envelope->labeltype(FL_NORMAL_LABEL);
      envelope->labelfont(0);
      envelope->labelsize(10);
      envelope->labelcolor(FL_FOREGROUND_COLOR);
      envelope->callback((Fl_Callback*)cb_envelope);
      envelope->align(Fl_Align(FL_ALIGN_BOTTOM));
      envelope->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* envelope
    { distortion = new Avtk::Dial(31, 169, 37, 37, "Distortion");
      distortion->box(FL_NO_BOX);
      distortion->color((Fl_Color)90);
      distortion->selection_color(FL_INACTIVE_COLOR);
      distortion->labeltype(FL_NORMAL_LABEL);
      distortion->labelfont(0);
      distortion->labelsize(10);
      distortion->labelcolor(FL_FOREGROUND_COLOR);
      distortion->callback((Fl_Callback*)cb_distortion);
      distortion->align(Fl_Align(FL_ALIGN_BOTTOM));
      distortion->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* distortion
    window->color( fl_rgb_color( 17, 17, 17) );
    close_cb( o, 0 );
    window->end();
  } // Fl_Double_Window* window
}

void Widget::idle() {
  Fl::check();
  Fl::flush();
}

int Widget::getWidth() {
  return window->w();
}

int Widget::getHeight() {
  return window->h();
}

void Widget::writePort(int port, float& value) {
  //cout << "port " << port << " value " << value << endl;
  write_function(controller, port, sizeof(float), 0, &value);
}

void Widget::close_cb(Fl_Widget* o, void*) {
  if ((Fl::event() == FL_KEYDOWN || Fl::event() == FL_SHORTCUT) && Fl::event_key() == FL_Escape)
    {
      return; // ignore ESC
    }
    else
    {
      o->hide();
    }
}
