// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "widget.h"

void CaptaWidget::cb_headerImage_i(Avtk::Image*, void*) {
  //system("xdg-open http://www.openavproductions.com/artyfx#ducka");
}
void CaptaWidget::cb_headerImage(Avtk::Image* o, void* v) {
  ((CaptaWidget*)(o->parent()->user_data()))->cb_headerImage_i(o,v);
}

void CaptaWidget::cb_graph_i(Avtk::Record* o, void*) {
  float tmp = o->value();
//rec->value( tmp );
//writePort(DRIVA_AMOUNT, tmp);

//volume->value( o->getVolume() );

float a = o->getActive();
//writePort(BITTA_ACTIVE, a);
//printf("active %f\n", a );
}
void CaptaWidget::cb_graph(Avtk::Record* o, void* v) {
  ((CaptaWidget*)(o->parent()->user_data()))->cb_graph_i(o,v);
}

void CaptaWidget::cb_rec_i(Avtk::Button* o, void*) {
  float tmp = o->value();
graph->value( tmp > 0.4999 ? true : false );
writePort(CAPTA_RECORD, tmp);
}
void CaptaWidget::cb_rec(Avtk::Button* o, void* v) {
  ((CaptaWidget*)(o->parent()->user_data()))->cb_rec_i(o,v);
}

/**
   if the type of filter changes, this function will highlight the right button
*/
void CaptaWidget::update_button(int button) {
}

CaptaWidget::CaptaWidget() {
  { Fl_Double_Window* o = window = new Fl_Double_Window(160, 220);
    window->user_data((void*)(this));
    { headerImage = new Avtk::Image(0, 0, 160, 29, "header.png");
      headerImage->box(FL_NO_BOX);
      headerImage->color(FL_BACKGROUND_COLOR);
      headerImage->selection_color(FL_BACKGROUND_COLOR);
      headerImage->labeltype(FL_NORMAL_LABEL);
      headerImage->labelfont(0);
      headerImage->labelsize(14);
      headerImage->labelcolor((Fl_Color)20);
      headerImage->callback((Fl_Callback*)cb_headerImage);
      headerImage->align(Fl_Align(FL_ALIGN_CENTER));
      headerImage->when(FL_WHEN_RELEASE_ALWAYS);
      headerImage->setPixbuf(header.pixel_data,4);
    } // Avtk::Image* headerImage
    { graph = new Avtk::Record(5, 36, 150, 126, "graph");
      graph->box(FL_UP_BOX);
      graph->color((Fl_Color)179);
      graph->selection_color(FL_INACTIVE_COLOR);
      graph->labeltype(FL_NO_LABEL);
      graph->labelfont(0);
      graph->labelsize(14);
      graph->labelcolor(FL_FOREGROUND_COLOR);
      graph->callback((Fl_Callback*)cb_graph);
      graph->align(Fl_Align(FL_ALIGN_BOTTOM));
      graph->when(FL_WHEN_CHANGED);
    } // Avtk::Record* graph
    { rec = new Avtk::Button(10, 169, 138, 35, "Record");
      rec->box(FL_NO_BOX);
      rec->color((Fl_Color)90);
      rec->selection_color(FL_INACTIVE_COLOR);
      rec->labeltype(FL_NORMAL_LABEL);
      rec->labelfont(0);
      rec->labelsize(14);
      rec->labelcolor(FL_FOREGROUND_COLOR);
      rec->callback((Fl_Callback*)cb_rec);
      rec->align(Fl_Align(FL_ALIGN_CENTER));
      rec->when(FL_WHEN_CHANGED);
    } // Avtk::Button* rec
    window->color( fl_rgb_color( 17, 17, 17) );
    close_cb( o, 0 );
    window->end();
  } // Fl_Double_Window* window
}

void CaptaWidget::idle() {
  Fl::check();
  Fl::flush();
}

int CaptaWidget::getWidth() {
  return window->w();
}

int CaptaWidget::getHeight() {
  return window->h();
}

void CaptaWidget::writePort(int port, float& value) {
  //cout << "port " << port << " value " << value << endl;
  write_function(controller, port, sizeof(float), 0, &value);
}

void CaptaWidget::close_cb(Fl_Widget* o, void*) {
  if ((Fl::event() == FL_KEYDOWN || Fl::event() == FL_SHORTCUT) && Fl::event_key() == FL_Escape)
    {
      return; // ignore ESC
    }
    else
    {
      o->hide();
    }
}
