// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef widget_h
#define widget_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "lv2/lv2plug.in/ns/extensions/ui/ui.h"
#include "../dsp/shared.hxx"
#include "avtk.h"
#include <stdio.h>
#include "header.c"
using namespace std;
#include <iostream>

class Widget {
public:
  void update_button(int button);
  Widget();
  Fl_Double_Window *window;
  Avtk::Image *headerImage;
private:
  void cb_headerImage_i(Avtk::Image*, void*);
  static void cb_headerImage(Avtk::Image*, void*);
public:
  Avtk::Dial *masterGain;
private:
  void cb_masterGain_i(Avtk::Dial*, void*);
  static void cb_masterGain(Avtk::Dial*, void*);
public:
  Avtk::Parameteric *graph;
private:
  void cb_graph_i(Avtk::Parameteric*, void*);
  static void cb_graph(Avtk::Parameteric*, void*);
public:
  Avtk::Dial *s1gain;
private:
  void cb_s1gain_i(Avtk::Dial*, void*);
  static void cb_s1gain(Avtk::Dial*, void*);
public:
  Avtk::Dial *s2gain;
private:
  void cb_s2gain_i(Avtk::Dial*, void*);
  static void cb_s2gain(Avtk::Dial*, void*);
public:
  Avtk::Dial *s3gain;
private:
  void cb_s3gain_i(Avtk::Dial*, void*);
  static void cb_s3gain(Avtk::Dial*, void*);
public:
  Avtk::Dial *s4gain;
private:
  void cb_s4gain_i(Avtk::Dial*, void*);
  static void cb_s4gain(Avtk::Dial*, void*);
public:
  LV2UI_Write_Function write_function; 
  LV2UI_Controller controller; 
  void idle();
  int getWidth();
  int getHeight();
private:
  float gain; 
  float cutoff; 
  float Q; 
public:
  void writePort(int port, float& value);
  void close_cb(Fl_Widget* o, void*);
};
#endif
