// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef widget_h
#define widget_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "lv2/lv2plug.in/ns/extensions/ui/ui.h"
#include "../dsp/shared.hxx"
#include "avtk.h"
#include <stdio.h>
#include "header.c"
using namespace std;
#include <iostream>
#include <FL/Fl_Choice.H>

class DrivaWidget {
public:
  void update_button(int button);
  DrivaWidget();
  Fl_Double_Window *window;
  Avtk::Image *headerImage;
private:
  void cb_headerImage_i(Avtk::Image*, void*);
  static void cb_headerImage(Avtk::Image*, void*);
public:
  Avtk::Wah *graph;
private:
  void cb_graph_i(Avtk::Wah*, void*);
  static void cb_graph(Avtk::Wah*, void*);
public:
  Avtk::Dial *drive;
private:
  void cb_drive_i(Avtk::Dial*, void*);
  static void cb_drive(Avtk::Dial*, void*);
public:
  Avtk::Dial *freq;
private:
  void cb_freq_i(Avtk::Dial*, void*);
  static void cb_freq(Avtk::Dial*, void*);
public:
  Fl_Choice *tone;
  LV2UI_Write_Function write_function; 
  LV2UI_Controller controller; 
  void idle();
  int getWidth();
  int getHeight();
private:
  float gain; 
  float cutoff; 
  float Q; 
public:
  void writePort(int port, float& value);
  void close_cb(Fl_Widget* o, void*);
};
#endif
