// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "widget.h"

void DrivaWidget::cb_headerImage_i(Avtk::Image*, void*) {
  //system("xdg-open http://www.openavproductions.com/artyfx#ducka");
}
void DrivaWidget::cb_headerImage(Avtk::Image* o, void* v) {
  ((DrivaWidget*)(o->parent()->user_data()))->cb_headerImage_i(o,v);
}

void DrivaWidget::cb_graph_i(Avtk::Wah* o, void*) {
  float tmp = o->value();
freq->value( tmp );
writePort(DRIVA_AMOUNT, tmp);

//volume->value( o->getVolume() );

float a = o->getActive();
//writePort(BITTA_ACTIVE, a);
//printf("active %f\n", a );
}
void DrivaWidget::cb_graph(Avtk::Wah* o, void* v) {
  ((DrivaWidget*)(o->parent()->user_data()))->cb_graph_i(o,v);
}

void DrivaWidget::cb_drive_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
graph->drive( tmp );
//writePort(WHAAA_DRIVE, tmp);
//printf("%f\n",tmp);
}
void DrivaWidget::cb_drive(Avtk::Dial* o, void* v) {
  ((DrivaWidget*)(o->parent()->user_data()))->cb_drive_i(o,v);
}

void DrivaWidget::cb_freq_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
graph->value( tmp );
writePort(DRIVA_AMOUNT, tmp);
//printf("%f\n",tmp);
}
void DrivaWidget::cb_freq(Avtk::Dial* o, void* v) {
  ((DrivaWidget*)(o->parent()->user_data()))->cb_freq_i(o,v);
}

/**
   if the type of filter changes, this function will highlight the right button
*/
void DrivaWidget::update_button(int button) {
}

DrivaWidget::DrivaWidget() {
  { Fl_Double_Window* o = window = new Fl_Double_Window(160, 220);
    window->user_data((void*)(this));
    { headerImage = new Avtk::Image(0, 0, 160, 29, "header.png");
      headerImage->box(FL_NO_BOX);
      headerImage->color(FL_BACKGROUND_COLOR);
      headerImage->selection_color(FL_BACKGROUND_COLOR);
      headerImage->labeltype(FL_NORMAL_LABEL);
      headerImage->labelfont(0);
      headerImage->labelsize(14);
      headerImage->labelcolor((Fl_Color)20);
      headerImage->callback((Fl_Callback*)cb_headerImage);
      headerImage->align(Fl_Align(FL_ALIGN_CENTER));
      headerImage->when(FL_WHEN_RELEASE_ALWAYS);
      headerImage->setPixbuf(header.pixel_data,4);
    } // Avtk::Image* headerImage
    { graph = new Avtk::Wah(5, 36, 150, 126, "graph");
      graph->box(FL_UP_BOX);
      graph->color((Fl_Color)179);
      graph->selection_color(FL_INACTIVE_COLOR);
      graph->labeltype(FL_NO_LABEL);
      graph->labelfont(0);
      graph->labelsize(14);
      graph->labelcolor(FL_FOREGROUND_COLOR);
      graph->callback((Fl_Callback*)cb_graph);
      graph->align(Fl_Align(FL_ALIGN_BOTTOM));
      graph->when(FL_WHEN_CHANGED);
    } // Avtk::Wah* graph
    { drive = new Avtk::Dial(78, 167, 38, 38, "Drive");
      drive->box(FL_NO_BOX);
      drive->color((Fl_Color)90);
      drive->selection_color(FL_INACTIVE_COLOR);
      drive->labeltype(FL_NORMAL_LABEL);
      drive->labelfont(0);
      drive->labelsize(10);
      drive->labelcolor(FL_FOREGROUND_COLOR);
      drive->callback((Fl_Callback*)cb_drive);
      drive->align(Fl_Align(FL_ALIGN_BOTTOM));
      drive->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* drive
    { freq = new Avtk::Dial(120, 167, 38, 38, "Amount");
      freq->box(FL_NO_BOX);
      freq->color((Fl_Color)90);
      freq->selection_color(FL_INACTIVE_COLOR);
      freq->labeltype(FL_NORMAL_LABEL);
      freq->labelfont(0);
      freq->labelsize(10);
      freq->labelcolor(FL_FOREGROUND_COLOR);
      freq->callback((Fl_Callback*)cb_freq);
      freq->align(Fl_Align(FL_ALIGN_BOTTOM));
      freq->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* freq
    { Fl_Choice* o = new Fl_Choice(0, 175, 73, 25, "Tone");
      o->down_box(FL_BORDER_BOX);
      o->align(Fl_Align(FL_ALIGN_BOTTOM));
    } // Fl_Choice* o
    window->color( fl_rgb_color( 17, 17, 17) );
    close_cb( o, 0 );
    window->end();
  } // Fl_Double_Window* window
}

void DrivaWidget::idle() {
  Fl::check();
  Fl::flush();
}

int DrivaWidget::getWidth() {
  return window->w();
}

int DrivaWidget::getHeight() {
  return window->h();
}

void DrivaWidget::writePort(int port, float& value) {
  //cout << "port " << port << " value " << value << endl;
  write_function(controller, port, sizeof(float), 0, &value);
}

void DrivaWidget::close_cb(Fl_Widget* o, void*) {
  if ((Fl::event() == FL_KEYDOWN || Fl::event() == FL_SHORTCUT) && Fl::event_key() == FL_Escape)
    {
      return; // ignore ESC
    }
    else
    {
      o->hide();
    }
}
