// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "widget.h"

void WhaaaWidget::cb_headerImage_i(Avtk::Image*, void*) {
  //system("xdg-open http://www.openavproductions.com/artyfx#ducka");
}
void WhaaaWidget::cb_headerImage(Avtk::Image* o, void* v) {
  ((WhaaaWidget*)(o->parent()->user_data()))->cb_headerImage_i(o,v);
}

void WhaaaWidget::cb_graph_i(Avtk::Wah* o, void*) {
  float tmp = o->value();
freq->value( tmp );
writePort(WHAAA_FREQ, tmp);

//volume->value( o->getVolume() );

float a = o->getActive();
//writePort(BITTA_ACTIVE, a);
//printf("active %f\n", a );
}
void WhaaaWidget::cb_graph(Avtk::Wah* o, void* v) {
  ((WhaaaWidget*)(o->parent()->user_data()))->cb_graph_i(o,v);
}

void WhaaaWidget::cb_freq_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
graph->value( tmp );
writePort(WHAAA_FREQ, tmp);
//printf("%f\n",tmp);
}
void WhaaaWidget::cb_freq(Avtk::Dial* o, void* v) {
  ((WhaaaWidget*)(o->parent()->user_data()))->cb_freq_i(o,v);
}

void WhaaaWidget::cb_range_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
//graph->value( tmp );
writePort(WHAAA_RANGE, tmp);
//printf("%f\n",tmp);
}
void WhaaaWidget::cb_range(Avtk::Dial* o, void* v) {
  ((WhaaaWidget*)(o->parent()->user_data()))->cb_range_i(o,v);
}

void WhaaaWidget::cb_mix_i(Avtk::Dial* o, void*) {
  float tmp = o->value();
//graph->value( tmp );
writePort(WHAAA_MIX, tmp);
//printf("%f\n",tmp);
}
void WhaaaWidget::cb_mix(Avtk::Dial* o, void* v) {
  ((WhaaaWidget*)(o->parent()->user_data()))->cb_mix_i(o,v);
}

/**
   if the type of filter changes, this function will highlight the right button
*/
void WhaaaWidget::update_button(int button) {
}

WhaaaWidget::WhaaaWidget() {
  { Fl_Double_Window* o = window = new Fl_Double_Window(160, 220);
    window->user_data((void*)(this));
    { headerImage = new Avtk::Image(0, 0, 160, 29, "header.png");
      headerImage->box(FL_NO_BOX);
      headerImage->color(FL_BACKGROUND_COLOR);
      headerImage->selection_color(FL_BACKGROUND_COLOR);
      headerImage->labeltype(FL_NORMAL_LABEL);
      headerImage->labelfont(0);
      headerImage->labelsize(14);
      headerImage->labelcolor((Fl_Color)20);
      headerImage->callback((Fl_Callback*)cb_headerImage);
      headerImage->align(Fl_Align(FL_ALIGN_CENTER));
      headerImage->when(FL_WHEN_RELEASE_ALWAYS);
      headerImage->setPixbuf(header.pixel_data,4);
    } // Avtk::Image* headerImage
    { graph = new Avtk::Wah(5, 36, 150, 126, "graph");
      graph->box(FL_UP_BOX);
      graph->color((Fl_Color)179);
      graph->selection_color(FL_INACTIVE_COLOR);
      graph->labeltype(FL_NO_LABEL);
      graph->labelfont(0);
      graph->labelsize(14);
      graph->labelcolor(FL_FOREGROUND_COLOR);
      graph->callback((Fl_Callback*)cb_graph);
      graph->align(Fl_Align(FL_ALIGN_BOTTOM));
      graph->when(FL_WHEN_CHANGED);
    } // Avtk::Wah* graph
    { freq = new Avtk::Dial(113, 167, 38, 38, "Wah");
      freq->box(FL_NO_BOX);
      freq->color((Fl_Color)90);
      freq->selection_color(FL_INACTIVE_COLOR);
      freq->labeltype(FL_NORMAL_LABEL);
      freq->labelfont(0);
      freq->labelsize(10);
      freq->labelcolor(FL_FOREGROUND_COLOR);
      freq->callback((Fl_Callback*)cb_freq);
      freq->align(Fl_Align(FL_ALIGN_BOTTOM));
      freq->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* freq
    { range = new Avtk::Dial(13, 166, 38, 38, "Range");
      range->box(FL_NO_BOX);
      range->color((Fl_Color)90);
      range->selection_color(FL_INACTIVE_COLOR);
      range->labeltype(FL_NORMAL_LABEL);
      range->labelfont(0);
      range->labelsize(10);
      range->labelcolor(FL_FOREGROUND_COLOR);
      range->callback((Fl_Callback*)cb_range);
      range->align(Fl_Align(FL_ALIGN_BOTTOM));
      range->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* range
    { mix = new Avtk::Dial(62, 167, 38, 38, "Mix");
      mix->box(FL_NO_BOX);
      mix->color((Fl_Color)90);
      mix->selection_color(FL_INACTIVE_COLOR);
      mix->labeltype(FL_NORMAL_LABEL);
      mix->labelfont(0);
      mix->labelsize(10);
      mix->labelcolor(FL_FOREGROUND_COLOR);
      mix->callback((Fl_Callback*)cb_mix);
      mix->align(Fl_Align(FL_ALIGN_BOTTOM));
      mix->when(FL_WHEN_CHANGED);
    } // Avtk::Dial* mix
    window->color( fl_rgb_color( 17, 17, 17) );
    close_cb( o, 0 );
    window->end();
  } // Fl_Double_Window* window
}

void WhaaaWidget::idle() {
  Fl::check();
  Fl::flush();
}

int WhaaaWidget::getWidth() {
  return window->w();
}

int WhaaaWidget::getHeight() {
  return window->h();
}

void WhaaaWidget::writePort(int port, float& value) {
  //cout << "port " << port << " value " << value << endl;
  write_function(controller, port, sizeof(float), 0, &value);
}

void WhaaaWidget::close_cb(Fl_Widget* o, void*) {
  if ((Fl::event() == FL_KEYDOWN || Fl::event() == FL_SHORTCUT) && Fl::event_key() == FL_Escape)
    {
      return; // ignore ESC
    }
    else
    {
      o->hide();
    }
}
