// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ducka_widget_h
#define ducka_widget_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "lv2/lv2plug.in/ns/extensions/ui/ui.h"
#include "avtk.h"
using namespace std;
#include <stdio.h>
#include "header.c"
#include "../dsp/shared.hxx"

class DuckaUI {
public:
  void update_button(int button);
  DuckaUI();
  Fl_Double_Window *window;
  Avtk::Image *headerImage;
private:
  void cb_headerImage_i(Avtk::Image*, void*);
  static void cb_headerImage(Avtk::Image*, void*);
public:
  Avtk::SidechainGain *graph;
private:
  void cb_graph_i(Avtk::SidechainGain*, void*);
  static void cb_graph(Avtk::SidechainGain*, void*);
public:
  Avtk::Dial *threshold;
private:
  void cb_threshold_i(Avtk::Dial*, void*);
  static void cb_threshold(Avtk::Dial*, void*);
public:
  Avtk::Dial *drop;
private:
  void cb_drop_i(Avtk::Dial*, void*);
  static void cb_drop(Avtk::Dial*, void*);
public:
  Avtk::Dial *time;
private:
  void cb_time_i(Avtk::Dial*, void*);
  static void cb_time(Avtk::Dial*, void*);
public:
  LV2UI_Write_Function write_function; 
  LV2UI_Controller controller; 
  void idle();
  int getWidth();
  int getHeight();
private:
  float gain; 
  float cutoff; 
  float Q; 
public:
  void writePort(int port, float& value);
  void close_cb(Fl_Widget* o, void*);
};
#endif
